### Obtener todas las comidas
GET http://localhost:3000/foods

### Recuperar una comidas por ID
GET http://localhost:3000/foods/b1d23c3b-9045-11ee-a213-fc4596eaaaef

### Recuperar todas las comidas por un tipo
GET http://localhost:3000/foods?type=drink

### Crear una comidas con POST
POST http://localhost:3000/foods
Content-Type: application/json

{
  "name": "pollo",
  "title": "Pollo a la mostaza",
  "price": 2000,
  "image": "https://i.pinimg.com/564x/be/0c/13/be0c1348d475af53d1cea012fb0522dd.jpg",
  "type": ["lunch"],
  "description": "Riquisimo con papas"
}

### Actualizar una comida

PATCH http://localhost:3000/foods/9dc65d2d-92f5-11ee-a726-fc4596eaaaef
Content-Type: application/json

{
  "name" : "Copa piston",
  "title": "Copa piston",
  "price": 2130,
  "image": "https://i.pinimg.com/564x/be/0c/13/be0c1348d475af53d1cea012fb0522dd.jpg"
}

### Borrar una comida
DELETE http://localhost:3000/foods/e4c35e43-92d0-11ee-a726-fc4596eaaaef