### Obtener todas las comidas
GET http://localhost:3000/foods

### Recuperar una comidas por ID
GET http://localhost:3000/foods/a4a2df6a-8e8d-4b9a-a80c-6a5480c6828e

### Recuperar todas las comidas por un tipo
GET http://localhost:3000/foods?type=cake

### Crear una comidas con POST
POST http://localhost:3000/foods
Content-Type: application/json

{
  "name": "Cars",
  "price": 1050,
  "title": "Cars la mejor peli",
  "image": "https://i.pinimg.com/564x/be/0c/13/be0c1348d475af53d1cea012fb0522dd.jpg",
  "type": ["lunch"],
  "description": "lo que sea"
}

### Actualizar una comida

PATCH http://localhost:3000/foods/3f55cf4b-1b3e-4f33-bb12-7d1215220b89
Content-Type: application/json

{
    "price": 2090
}

### Borrar una comida
DELETE http://localhost:3000/foods/a4a2df6a-8e8d-4b9a-a80c-6a5480c6828e